### ISSUE TITLE
Black versions of moon phases symbols are not readable (from 1F311 to 1F318)

### ISSUE THREAD

**Issue by doriantimmermans** [hfg-gmuend/openmoji#387]
When using the OpenMoji-Black font, the moon phases symbols are not readable because only the outlines are kept.
We can't tell which part is the lighted side of the moon and which one is the shadow side, so for example full moon looks exactly like new moon.

![Screenshot 2022-04-24 at 17-24-38](https://user-images.githubusercontent.com/52008966/164983768-cffd44a4-f5d1-4eda-a7ee-cf2396a31dc9.png)

(also it seems there is something weird happening with 1F317, the yellow fill going outside of the outlines)

**Comment by b-g** [comment]
Many thanks for the feedback! 

- Yes 1F317 is buggy ... but the fonts are experimental and not for production. We are really struggling with the color font generation part, see the epic conversation e.g. here #260. Hence it makes no sense to invest any time in it, as a better colorfont build system might be able to deal with it
- Yes it would be better to show all yellow shapes in black for OpenMoji-Black. A PR to fix this would be welcome :)

**Comment by RobertWinslow** [comment]
Here's a comparison of how these characters are being rendered in the current version of the fonts.
(In Chrome for MacOS)

From left to right: color png, glyf_colr_0 font, system default, black png, black glyf font

![Screen Shot 2023-01-14 at 10 59 20 AM](https://user-images.githubusercontent.com/5784659/212485231-a75d5c07-f274-4f0c-a02e-1a20542700d7.png)![Screen Shot 2023-01-14 at 11 04 33 AM](https://user-images.githubusercontent.com/5784659/212485558-2d4e46c6-c63d-4c77-9921-39343026fefd.png)

**Comment by lizbravob** [comment]
Hi 👋🏼 I hope this helps 🌕🌖🌗🌘🌑🌒🌓🌔
[moon.zip](https://github.com/hfg-gmuend/openmoji/files/10421537/moon.zip)

**Comment by b-g** [comment]
@RobertWinslow I guess your intention was to show with the table that the issues has been resolved, correct?

@lizbravob Many thanks! Probably I'm blind, but what is different in comparison to the table above? 🤷‍♂️ :)

**Comment by lizbravob** [comment]
Oh sorry! I got confused. I thought it might help if the moon phases emojis used the special layer line-supplement for the dark mode.

**Comment by RobertWinslow** [comment]
> the issues has been resolved, correct?
Yes, kind of. The color font is perfect, and #426 added black elements to
the line-supplement layer, as shown in the PNG column.
On the other hand, The black font still isn't rendering some of the glyphs
in a difficult-to-read way, but that's a subset of the problem described in
#433.
